### ISSUE TITLE
phone null already exists in database

### ISSUE THREAD

**Issue by Cabalforces** [Comet-App/comet#91]
![Screenshot_20210509-132355~2.png](https://user-images.githubusercontent.com/2729035/117572640-b0715880-b0cb-11eb-985d-12ad22a9fda3.png)

There is no input for it beforehand.

**Comment by akay25** [comment]
Thanks for opening the issue.
We did tested the registration flow before pushing the changes but it seems to be having some problems.

We will fix it asap.

**Comment by akay25** [comment]
Please try now, it was issue with database.

**Comment by Cabalforces** [comment]
It worked. Thank you!
